name: Invo CI/CD
on: [push]

jobs:
  Hostaway_job:
    name: Deploy invo job 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout invo to the github action runner
        uses: actions/checkout@v3

      - name: SSH connect and deploy Invo to the remote EC2 instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -la
            git clone https://github.com/phalcon/invo.git
            echo "================"
            cd invo/
            cp .env.example .env
            sed -i "s/localhost/${{ RDS_ADDRESS }}/g" .env
            sed -i "s/phalcon_invo/${{ RDS_DBNAME }}/g" .env
            sed -i "0,/phalcon/{s/phalcon/${{ RDS_USER }}/}" .env
            sed -i "s/secret/${{ RDS_PASSWORD }}/g" .env

