name: Invo CI/CD
on: [push]

jobs:
  Deploy:
    name: Desploy invo to EC2 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to the remote server
        uses: easingthemes/ssh-deploy@v2
        env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
           REMOTE_USER: ${{ secrets.REMOTE_USER }}
           TARGET: ${{ secrets.REMOTE_TARGET }}
           SCRIPT_BEFORE: |
             whoami
             ls -al
             touch /home/ubuntu/justbefore
           SCRIPT_AFTER: |
             whoami
             ls -al
             echo $RSYNC_STDOUT
             touch /home/ubuntu/justafter
