name: Invo CI/CD
on: [push]

jobs:
  Hostaway job:
    name: Desploy invo job 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout invo to the github action runner
        uses: actions/checkout@v3

      - name: SSH connect and deploy Invo to the remote EC2 instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pwd
            touch hello.txt
            ls -la
