name: Invo CI/CD
on: [push]

jobs:
  Deploy:
    name: Desploy invo to EC2 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to the remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -la
