name: Invo CI/CD
on: [push]

jobs:
  Hostaway_job:
    name: Deploy invo job 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout invo to the github action runner
        uses: actions/checkout@v3

      - name: SSH connect and deploy Invo to the remote EC2 instance
        uses: appleboy/ssh-action@v1.0.0

        env:
          RDS_ADDRESS: ${{ secrets.RDS_ADDRESS }}
          RDS_DBNAME: ${{ secrets.RDS_DBNAME }}
          RDS_USER: ${{ secrets.RDS_USER }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}

        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: RDS_ADDRESS,RDS_DBNAME,RDS_USER,RDS_PASSWORD
          script: |
            ls -a
            git clone https://github.com/phalcon/invo.git
            echo "================"
            cd invo/
            cp .env.example .env
            sed -i "s/localhost/$RDS_ADDRESS/g" .env
            sed -i "s/phalcon_invo/$RDS_DBNAME/g" .env
            sed -i "s/secret/$RDS_PASSWORD/g" .env
            sed -i "0,/phalcon/{s/phalcon/$RDS_USER/}" .env
